### ISSUE TITLE
AttributeError: 'ReacherMILEnv' object has no attribute 'viewer'

### ISSUE THREAD

**Issue by HongminWu** [tianheyu927/mil#17]
Traceback (most recent call last):
  File "/home/user/gym-mil/gym/core.py", line 203, in __del__
    self.close()
  File "/home/user/gym-mil/gym/core.py", line 164, in close
    self.render(close=True)
  File "/home/user/gym-mil/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/user/gym-mil/gym/envs/mujoco/mujoco_env.py", line 104, in _render
    if self.viewer is not None:
AttributeError: 'ReacherMILEnv' object has no attribute 'viewer'

What makes this error?
Hope some tips,thanks.

**Comment by daiyk** [comment]
Try a different version of mujoco, it seems like your mujoco has a problem

**Comment by tuonan** [comment]
Hi.Do you solve this problem?
