### ISSUE TITLE
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32

### ISSUE THREAD

**Issue by niudong1001** [tianheyu927/mil#8]
Hello, I run your code and just got the following error:
```bash
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    main()
  File "main.py", line 268, in main
    train_image_tensors = data_generator.make_batch_tensor(network_config, restore_iter=FLAGS.restore_iter)
  File "/media/niudong/资源/Projects/mil/data_generator.py", line 216, in make_batch_tensor
    filename_queue = tf.train.string_input_producer(tf.convert_to_tensor(all_filenames), shuffle=False)
  File "/home/niudong/workon_home/milpy2/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 245, in string_input_producer
    string_tensor = ops.convert_to_tensor(string_tensor, dtype=dtypes.string)
  File "/home/niudong/workon_home/milpy2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1048, in convert_to_tensor
    as_ref=False)
  File "/home/niudong/workon_home/milpy2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/niudong/workon_home/milpy2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 981, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("Const:0", shape=(0,), dtype=float32)'
```
I guess if it happened because of tensorflow version and I used `tf1.11`.
Hope to find some cues!

Thanks
Best Wishes

**Comment by 11201112** [comment]
I found the same issue as you. Have you solved it?

Thanks
Best wishes to you!

**Comment by tianheyu927** [comment]
Yeah, I think this is caused by tensorflow version. The code uses `tf1.4`.
