### ISSUE TITLE
run_sim_push_video_only.sh: line 8: --temporal_num_layers=3: command not found

### ISSUE THREAD

**Issue by ngalym** [tianheyu927/mil#9]
HI, there is a list of errors occurring when I try to launch the scripts. This is the piece of error list when the run_sim_push_video_only.sh: is launched. Is it a tensorflow version problem? Tried the solution here [https://github.com/tensorflow/models/issues/3705#issuecomment-375563179](url) but still didn't help. Can you please look what could be the problem and solution?
`
Number of demos: 9228
TIMER:data_generator.py:extract_supervised_data: Normalizing states (Elapsed: 0.966589s)
 TIMER:data_generator.py:generate_batches: Generating batches for each iteration (Elapsed: 661.176920s)
WARNING:tensorflow:From ~/daml/mil/data_generator.py:194: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by ``tf.data``. Use tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If shuffle=False, omit the .shuffle(...).
WARNING:tensorflow:From ~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/training/input.py:276: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by ``tf.data``. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From ~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/training/input.py:188: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by ``tf.data``. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From ~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/training/input.py:197: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the ``tf.data`` module.
WARNING:tensorflow:From ~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/training/input.py:197: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the ``tf.data`` module.
Generating image processing ops
WARNING:tensorflow:From ~/daml/mil/data_generator.py:196: WholeFileReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by ``tf.data``. Use `tf.data.Dataset.map(tf.read_file)`.
Batching images
WARNING:tensorflow:From ~/daml/mil/data_generator.py:225: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by ``tf.data``. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
Generating image processing ops
Batching images
TIMER:mil.py:init_network: building TF network (Elapsed: 9.237436s)
Traceback (most recent call last):
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2673, in gather
    return params.sparse_read(indices, name=name)
AttributeError: 'Tensor' object has no attribute 'sparse_read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 451, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: range(0, 20) - got shape [20], but wanted [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 451, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: range(0, 20) - got shape [20], but wanted [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 314, in <module>
    main()
  File "main.py", line 280, in main
    model.init_network(graph, input_tensors=train_input_tensors, restore_iter=FLAGS.restore_iter)
  File "~/daml/mil/mil.py", line 36, in init_network
    result = self.construct_model(input_tensors=input_tensors, prefix=prefix, dim_input=self._dO, dim_output=self._dU, network_config=self.network_params)
  File "~/daml/mil/mil.py", line 630, in construct_model
    unused = batch_metalearn((inputa[0], inputb[0], actiona[0], actionb[0]))
  File "~/daml/mil/mil.py", line 516, in batch_metalearn
    local_outputa, final_eept_preda = self.forward((inputa), state_inputa, weights, network_config=network_config)
  File "~/daml/mil/mil.py", line 252, in forward
    context = tf.transpose(tf.gather(tf.transpose(tf.zeros_like(flatten_image)), range(FLAGS.bt_dim)))
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2675, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3332, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "~/daml/mil/.env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'indices' to a tensor and failed. Error: Argument must be a dense tensor: range(0, 20) - got shape [20], but wanted [].
./scripts/run_sim_push_video_only.sh: line 8: --temporal_num_layers=3: command not found
(.env) user@daml:~/daml/mil$  
`

**Comment by tianheyu927** [comment]
I believe this is a tensorflow version problem. The code is using tf v1.4.

**Comment by ngalym** [comment]
> I believe this is a tensorflow version problem. The code is using tf v1.4.

the same error with tf v1.4 
`./scripts/run_sim_push_video_only.sh: line 8: --temporal_num_layers=3: command not found
`

**Comment by tianheyu927** [comment]
I don't think this error would affect training
